In [4]:
#%load_ext line_profiler
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [9]:
import numpy as np 
import serial
import serial.tools.list_ports as port_list
import matplotlib.pyplot as plt 
%matplotlib qt

## Hanging Robot 

In [10]:
from robot_controls import * 
#from Camera import *

GUI = control_gui("Art")

In [30]:
GUI = control_gui("Art")
                

No Port Found
[[ 10. 400.   0.]
 [ 10. 400. 350.]
 [310. 400. 350.]
 [310. 400. 279.]
 [269. 400. 279.]
 [269. 400.  49.]
 [ 89. 400.  49.]]
[]
[]
[array([105.73591349, 231.61781446,  49.        ])]
[array([105.73591349, 231.61781446,  49.        ])]
[array([105.73591349, 231.61781446,  49.        ]), array([105.73591349, 205.44270537, 258.08290647])]
[105.73591349 231.61781446  49.        ]
[105.73591349 205.44270537 258.08290647]
105.73591348890164 231.61781445646002
105.7359134889017 205.44270536900055
[105.73591349 231.61781446  49.        ]
[105.73591349 205.44270537 258.08290647]
105.73591348890164 48.9999999999999
105.7359134889017 258.0829064693606
[105.73591349 231.61781446  49.        ]
[105.73591349 205.44270537 258.08290647]
231.61781445646002 48.9999999999999
205.44270536900055 258.0829064693606
[array([105.73591349, 231.61781446,  49.        ]), array([105.73591349, 205.44270537, 258.08290647])]
[105.73591349 231.61781446  49.        ]
[105.73591349 205.44270537 258.08290

In [7]:
GUI.motors.device

Serial<id=0x1fcbe38c160, open=False>(port='COM7', baudrate=9600, bytesize=8, parity='N', stopbits=1, timeout=0.1, xonxoff=False, rtscts=False, dsrdtr=False)

In [6]:
GUI = control_gui("Art", cameras = camid)

NameError: name 'camid' is not defined

In [5]:
import serial.tools.list_ports

# Clears lists
all_ports = []
comPorts = []
comPorts2 = []

# Fills lists with info
all_ports = list(port_list.comports())
comPorts = list(serial.tools.list_ports.comports())
#comPorts2 = list(serial.tools.list_ports.ListPortInfo)

# Prints info
print ("List of devices connected on com ports: " ,comPorts)
print([comport.device for comport in serial.tools.list_ports.comports()])
print("Hopefully information on the devices attached to the com ports: ", comPorts2)

List of devices connected on com ports:  [<serial.tools.list_ports_common.ListPortInfo object at 0x0000010DF00E8A90>]
['COM8']
Hopefully information on the devices attached to the com ports:  []


In [13]:
all_ports = list(port_list.comports())
pos_ports = [p.device for p in all_ports]
print(pos_ports)

['COM7']


In [ ]:
#finding device id
import win32com.client

 

wmi = win32com.client.GetObject ("winmgmts:")
for usb in wmi.InstancesOf ("Win32_USBHub"):
    print(usb.DeviceID)

In [ ]:
# importing libraries
import cv2
import numpy as np

# Create a VideoCapture object and read from input file
cap = cv2.VideoCapture(0)

# Check if camera opened successfully
if (cap.isOpened()== False):
    print("Error opening video file")

# Read until video is completed
while(cap.isOpened()):

    # Capture frame-by-frame
    ret, frame = cap.read()
    if ret == True:

        # Display the resulting frame
        cv2.imshow('Frame', frame)
    
        # Press Q on keyboard to exit
        if cv2.waitKey(25) & 0xFF == ord('q'):
            break

# Break the loop
    else:
        break

# When everything done, release
# the video capture object
cap.release()

# Closes all the frames
cv2.destroyAllWindows()


In [ ]:
GUI.motors.device.close()

In [ ]:
GUI.motors.read_info()

In [ ]:
GUI.run_commands(commands)

## Running Commands

In [ ]:
commands = []

p0 = GUI.get_position()
for i in range(100):
    
    p1 = p0 + np.array([0,0,50])*np.sin(np.pi*i/10)
    p1 = p1 + np.array([30,0,0])*np.sin(np.pi*i/10)
    p1 = p1 + np.array([0,30,0])*np.sin(np.pi*i/10)
    
    command = p1
    commands.append(command)

GUI.run_commands( commands )


In [ ]:
#Commands from camera 
robot_model = torch.load('.\\models\\robot_noise_2.pt',map_location=torch.device('cpu'))
mouse_model = torch.load('.\\models\\robot_mouse_2.pt',map_location=torch.device('cpu'))

img = CameraConnection.getNextFrame()
print(img)
cv2.imshow('img',img)
commands = []
folder = 'Test images/Robotarm noise'
filename_top = "41.jpg"
top = cv2.imread("./" + folder + "/" + filename_top)
filename_side = "32B.jpg"
side = cv2.imread("./" + folder + "/" + filename_side)
x,y,z = recon_3D(robot_model, side, top)
p0 = GUI.get_position_camera(robot_model,side,top)
print(p0)
for i in range(100):
    
    p1 = p0 + np.array([0,0,50])*np.sin(np.pi*i/10)
    p1 = p1 + np.array([30,0,0])*np.sin(np.pi*i/10)
    p1 = p1 + np.array([0,30,0])*np.sin(np.pi*i/10)
    
    command = p1
    commands.append(command)

GUI.run_commands( commands )


In [ ]:
GUI.command_queue

## SCARA

In [ ]:
#from robot_controls import * 
from Camera import *

In [ ]:
rob = Scara()

In [ ]:
import os
import numpy as np
import cv2
import time 
from datetime import datetime

def record_video(cam_id=0, record=True, outdir=None ):
    
    cap = cv2.VideoCapture(cam_id)
    fourcc = cv2.VideoWriter_fourcc(*'mp4v')
    
    if record:
        
        if outdir is None: outdir="..\\Camera_Out\\"
        if not os.path.exists(outdir):  os.makedirs(outdir )
        timestr = datetime.now().strftime("%Y%m%d_%H%M%S")
        fn_out = outdir + "\\" + timestr + ".mp4"
        out = cv2.VideoWriter(fn_out,fourcc, 20.0, (640,480))
        
    else: out=None

    while(cap.isOpened()):
        ret, frame = cap.read()
        if ret==True:
            cv2.imshow('frame',frame)
            if out is not None: out.write(frame)
            if cv2.waitKey(1) & 0xFF == ord('q'): break
        else: break

    if out: out.release()
    cap.release()
    cv2.destroyAllWindows()
    

In [ ]:
record_video(cam_id=1)

## Camera Controls

In [ ]:
cam=Camera(0)

## Testing

In [ ]:
all_ports = list(port_list.comports())
pos_ports = [p.device for p in all_ports  if "Arduino" in p.description]

In [ ]:
[print(port) for port in all_ports ]

In [ ]:
rob_mod.fig = None

In [ ]:

rob_mod.motor_rotation = [0,0,0,135,60,60]
rob_mod.compute_forward()
print(rob_mod.motor_rotation)
print(rob_mod.joint_pos)
rob_mod.draw_model()

In [ ]:
#pos = rob_mod.joint_pos[-1]
#rob_mod.compute_inverse(*pos)
#rob_mod.draw_model()
#print(rob_mod.motor_rotation)
#print(rob_mod.joint_pos)
#rob_mod.draw_model()

In [ ]:
pos = 300,200,200
rob_mod.compute_inverse(*pos)
rob_mod.draw_model()
print(rob_mod.motor_rotation)
print(rob_mod.joint_pos)

In [ ]:
det_to_input(260,250,110)