In [1]:
#%load_ext line_profiler
import os 


os.chdir("..")
print(os.getcwd())

# %load_ext line_profiler
%load_ext autoreload
%autoreload 2

C:\Users\eac84\Universiteit Antwerpen\Plasma Robotics - General\Robot_controls


In [2]:
import numpy as np 
import serial
import serial.tools.list_ports as port_list
import matplotlib.pyplot as plt 
%matplotlib qt

## Hanging Robot 

In [3]:
from robot_controls import * 
#from Camera import *

In [3]:
import serial
ard = serial.Serial("COM6", 9600, timeout=0.1)


In [4]:
cmd = bytearray("M 3 "" "+ str(100)+ "\r", "utf8")
ard.write(cmd) 

9

In [5]:
ard.close()

GUI = control_gui("Art")

In [4]:
GUI = control_gui()
                

No Port Found
[[ 10. 400.   0.]
 [ 10. 400. 350.]
 [310. 400. 350.]
 [310. 400. 279.]
 [269. 400. 279.]
 [269. 400.  49.]
 [ 89. 400.  49.]]
[]
[]
[]
[]
[]
[]
[]


In [4]:
print(os.getcwd())

C:\Users\yllik\Universiteit Antwerpen\Plasma Robotics - General\Controls\Robot_controls


In [6]:
GUI.motors.device.close()

In [36]:
record_video(cam_id=1)

bad frame
bad frame


KeyboardInterrupt: 

In [5]:
GUI = control_gui("Scara")

['COM5']
.
trying COM5 .............Device Info: Scara
Scara ...Port Found:  COM5

[]


In [17]:


for _ in range(10):
    
    cmd = bytearray("M 2 "+ str(5)+ "\r", "utf8")
    GUI.motors.device.write(cmd)

In [6]:
GUI.motors.device.close()

AttributeError: 'NoneType' object has no attribute 'close'

In [7]:
    cmd = bytearray("M 2 "+ str(10)+ "\r", "utf8")
    GUI.motors.device.write(cmd)

AttributeError: 'NoneType' object has no attribute 'write'

Clicked Out of Range
[]
Clicked Out of Range
[]
Clicked Out of Range
[]
Clicked Out of Range
[]
moving robot to 
-180 96 -90
0 -6 0
moving robot to 
0 0 0
0 -6 0
moving robot to 
0 0 0
0 -6 0


In [15]:
    cmd = bytearray("M 0 "+ str(-5)+ "\r", "utf8")
    GUI.motors.device.write(cmd)

8

In [12]:
import serial.tools.list_ports

# Clears lists
all_ports = []
comPorts = []
comPorts2 = []

# Fills lists with info
all_ports = list(port_list.comports())
comPorts = list(serial.tools.list_ports.comports())
#comPorts2 = list(serial.tools.list_ports.ListPortInfo)

# Prints info
print ("List of devices connected on com ports: " ,comPorts)
print([comport.device for comport in serial.tools.list_ports.comports()])
print("Hopefully information on the devices attached to the com ports: ", comPorts2)

KeyboardInterrupt: 

In [5]:
all_ports = list(port_list.comports())
pos_ports = [p.device for p in all_ports]
print(pos_ports)

['COM7']


In [ ]:
#finding device id
import win32com.client

 

wmi = win32com.client.GetObject ("winmgmts:")
for usb in wmi.InstancesOf ("Win32_USBHub"):
    print(usb.DeviceID)

In [8]:
ard = serial.Serial("COM6", 9600, timeout=0.1)

In [10]:
# Motor control, str is distance in mm
cmd = bytearray("M 2 "+ str(1000)+ "\r", "utf8")
ard.write(cmd) 
resp = ard.readline() 
# 
print(resp)

b'moving -888.96 degrees\r\n'


In [78]:
# importing libraries
import cv2
import numpy as np

# Create a VideoCapture object and read from input file
cap = cv2.VideoCapture(1)

# Check if camera opened successfully
if (cap.isOpened()== False):
    print("Error opening video file")

# Read until video is completed
while(cap.isOpened()):

    # Capture frame-by-frame
    ret, frame = cap.read()
    if ret == True:

        # Display the resulting frame
        cv2.imshow('Frame', frame)
    
        # Press Q on keyboard to exit
        if cv2.waitKey(25) & 0xFF == ord('q'):
            break

# Break the loop
    else:
        break

# When everything done, release
# the video capture object
cap.release()

# Closes all the frames
cv2.destroyAllWindows()


In [ ]:
GUI.motors.device.close()

In [ ]:
GUI.motors.read_info()

In [ ]:
GUI.run_commands(commands)

## Running Commands

In [ ]:
commands = []

p0 = GUI.get_position()
for i in range(100):
    
    p1 = p0 + np.array([0,0,50])*np.sin(np.pi*i/10)
    p1 = p1 + np.array([30,0,0])*np.sin(np.pi*i/10)
    p1 = p1 + np.array([0,30,0])*np.sin(np.pi*i/10)
    
    command = p1
    commands.append(command)

GUI.run_commands( commands )


In [ ]:
#Commands from camera 
robot_model = torch.load('.\\models\\robot_noise_2.pt',map_location=torch.device('cpu'))
mouse_model = torch.load('.\\models\\robot_mouse_2.pt',map_location=torch.device('cpu'))

img = CameraConnection.getNextFrame()
print(img)
cv2.imshow('img',img)
commands = []
folder = 'Test images/Robotarm noise'
filename_top = "41.jpg"
top = cv2.imread("./" + folder + "/" + filename_top)
filename_side = "32B.jpg"
side = cv2.imread("./" + folder + "/" + filename_side)
x,y,z = recon_3D(robot_model, side, top)
p0 = GUI.get_position_camera(robot_model,side,top)
print(p0)
for i in range(100):
    
    p1 = p0 + np.array([0,0,50])*np.sin(np.pi*i/10)
    p1 = p1 + np.array([30,0,0])*np.sin(np.pi*i/10)
    p1 = p1 + np.array([0,30,0])*np.sin(np.pi*i/10)
    
    command = p1
    commands.append(command)

GUI.run_commands( commands )


In [ ]:
GUI.command_queue

## SCARA

In [ ]:
#from robot_controls import * 
from Camera import *

In [ ]:
rob = Scara()

In [11]:
import os
import numpy as np
import cv2
import time 
from datetime import datetime

def record_video(cam_id=0, record=True, outdir=None ):
    
    cap = cv2.VideoCapture(cam_id)
    fourcc = cv2.VideoWriter_fourcc(*'mp4v')
    
    if record:
        
        if outdir is None: outdir="..\\Camera_Out\\"
        if not os.path.exists(outdir):  os.makedirs(outdir )
        timestr = datetime.now().strftime("%Y%m%d_%H%M%S")
        fn_out = outdir + "\\" + timestr + ".mp4"
        out = cv2.VideoWriter(fn_out,fourcc, 20.0, (640,480))
        
    else: out=None
    try:
        while(cap.isOpened()):
            ret, frame = cap.read()
            if ret==True and frame is not None:
                cv2.imshow('frame',frame)
                if out is not None: out.write(frame)
                if cv2.waitKey(1) & 0xFF == ord('q'): break
            else: 
                print("bad frame")
    except:   pass
    if out: out.release()
    cap.release()
    cv2.destroyAllWindows()
    

In [13]:
record_video(cam_id=1)

bad frame
bad frame
bad frame
bad frame
bad frame
bad frame
bad frame
bad frame
bad frame
bad frame
bad frame
bad frame


## Camera Controls

In [ ]:
cam=Camera(0)

## Testing

In [ ]:
all_ports = list(port_list.comports())
pos_ports = [p.device for p in all_ports  if "Arduino" in p.description]

In [ ]:
[print(port) for port in all_ports ]

In [ ]:
rob_mod.fig = None

In [ ]:

rob_mod.motor_rotation = [0,0,0,135,60,60]
rob_mod.compute_forward()
print(rob_mod.motor_rotation)
print(rob_mod.joint_pos)
rob_mod.draw_model()

In [ ]:
#pos = rob_mod.joint_pos[-1]
#rob_mod.compute_inverse(*pos)
#rob_mod.draw_model()
#print(rob_mod.motor_rotation)
#print(rob_mod.joint_pos)
#rob_mod.draw_model()

In [ ]:
pos = 300,200,200
rob_mod.compute_inverse(*pos)
rob_mod.draw_model()
print(rob_mod.motor_rotation)
print(rob_mod.joint_pos)

In [ ]:
det_to_input(260,250,110)